"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vut%f(hdmdz#_01ufk2ja0cg7djcqg)q=6@%g&c%6lwi672%+1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',

    'drf_spectacular',
    'rest_framework',
    'drf_spectacular_sidecar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "tests",
        "USER": "postgres",
        "PASSWORD": "1",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}
AUTH_USER_MODEL = 'shop.User'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis broker ishlatamiz
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = 'static/'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # Bir sahifada nechta element bo‘lishini belgilang

    # DRF Spectacular uchun default schema class
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

JAZZMIN_SETTINGS = {
    "site_title": "Nematov Admin",  # Sahifa title
    "site_header": "Nematov Panel",
    "site_brand": "Nematov",
    "welcome_sign": "Xush kelibsiz, Nematov Admin paneliga!",

    # LOGO VA ICONLAR
    "site_logo": "images/logo.png",  # Statik papkadagi logotip
    "site_logo_classes": "img-circle",  # Doira shaklidagi logo
    "site_icon": "images/favicon.ico",  # Favicon (tab belgisida chiqadigan rasm)
    "login_logo": "images/login_logo.png",
    "login_logo_dark": "images/login_logo_dark.png",

    # FON VA RANGLAR
    "theme": "cosmo",  # Bootstrap Theme (quyidagi variantlarni ishlatish mumkin)
    "custom_css": "css/custom.css",  # Maxsus CSS fayl
    "custom_js": "js/custom.js",  # Maxsus JavaScript

    # NAVBAR VA SIDEBAR SOZLAMALARI
    "navigation_expanded": True,  # Sidebar doim ochiq turishi
    "hide_apps": ["auth", "contenttypes"],  # Ba'zi app'larni yashirish
    "hide_models": ["auth.Group"],  # Ba'zi modellarni yashirish
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "shop.Product": "fas fa-shopping-cart",  # Ikonlar qo‘shish
        "shop.Order": "fas fa-receipt",
    },

    # FOYDALANUVCHI PROFILI
    "user_avatar": "profile.image",  # Foydalanuvchi uchun avatar
    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "shop"},
    ],

    # CHARTLAR (STATISTIKA)
    "analytics": {
        "shop.Order": {
            "type": "line",
            "data": {
                "labels": ["Yanvar", "Fevral", "Mart", "Aprel", "May"],
                "datasets": [
                    {
                        "label": "Buyurtmalar",
                        "data": [10, 25, 30, 40, 50],
                        "borderColor": "#ff6384",
                        "backgroundColor": "rgba(255, 99, 132, 0.2)",
                    }
                ],
            },
        }
    },

    # FORMALAR VA ADMIN PANEL UX
    "changeform_format": "horizontal_tabs",  # Formalarni tab shaklida qilish
    "changeform_format_overrides": {
        "shop.product": "collapsible",  # Yashirin bo‘lishi mumkin
    },

    # JAVASCRIPT VA CSS ULANISHI
    "css": {
        "external": [
            "/static/css/custom.css",
        ]
    },
    "js": {
        "external": [
            "/static/js/custom.js",
        ]
    },
}
